# Generated by Django 5.2.7 on 2025-11-03 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassNeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=100)),
                ("item", models.CharField(max_length=200)),
                ("quantity_needed", models.IntegerField()),
                ("cost_per_item", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["class_name"],
            },
        ),
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "donor_type",
                    models.CharField(
                        choices=[
                            ("Individual", "Individual"),
                            ("Corporate", "Corporate"),
                        ],
                        default="Individual",
                        max_length=20,
                    ),
                ),
                (
                    "total_donated",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("last_donation_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-total_donated"],
            },
        ),
        migrations.CreateModel(
            name="Expenditure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Supplies", "Supplies"),
                            ("Utilities", "Utilities"),
                            ("Staff", "Staff"),
                            ("Maintenance", "Maintenance"),
                        ],
                        default="Supplies",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=100)),
                ("quantity", models.IntegerField(default=0)),
                ("low_stock_threshold", models.IntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RegisteredDonor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mobile_number", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("password_plaintext", models.CharField(max_length=100)),
                (
                    "donation_frequency",
                    models.CharField(
                        choices=[("Annual", "Annual"), ("Semi-Annual", "Semi-Annual")],
                        default="Annual",
                        max_length=20,
                    ),
                ),
                (
                    "amount_pledged",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("age", models.IntegerField()),
                ("class_name", models.CharField(max_length=100)),
                ("school", models.CharField(max_length=200)),
                (
                    "parental_income",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "help_provided",
                    models.TextField(
                        help_text="Kind of help provided (e.g., books, money, school dress)"
                    ),
                ),
                (
                    "performance",
                    models.CharField(
                        choices=[
                            ("Excellent", "Excellent"),
                            ("Good", "Good"),
                            ("Average", "Average"),
                            ("Needs Improvement", "Needs Improvement"),
                        ],
                        default="Average",
                        max_length=20,
                    ),
                ),
                (
                    "sponsorship_status",
                    models.CharField(
                        choices=[
                            ("Sponsored", "Sponsored"),
                            ("Not Sponsored", "Not Sponsored"),
                        ],
                        default="Not Sponsored",
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sponsor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sponsored_students",
                        to="core.registereddonor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
