# Generated by Django 5.2.7 on 2025-11-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_adminuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="registereddonor",
            name="desired_donation",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount donor currently wants to donate",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="registereddonor",
            name="last_donation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registereddonor",
            name="total_donated",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total amount donated so far",
                max_digits=10,
            ),
        ),
    ]
