# Generated by Django 5.2.7 on 2025-11-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_admin_delete_adminuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registereddonor",
            name="donation_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Annual", "Annual"),
                    ("Half-yearly", "Half-yearly"),
                    ("N/A", "N/A (One-time donor)"),
                ],
                default="N/A",
                max_length=20,
                null=True,
            ),
        ),
    ]
