# Generated by Django 5.2.7 on 2025-11-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_registereddonor_donation_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registereddonor",
            name="amount_pledged",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="registereddonor",
            name="desired_donation",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount donor currently wants to donate",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="registereddonor",
            name="total_donated",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total amount donated so far",
                max_digits=12,
            ),
        ),
    ]
