# Generated by Django 4.2.7 on 2025-11-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_fix_invalid_donation_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="mobile_number",
            field=models.CharField(
                blank=True,
                help_text="Mobile number with country code (e.g., +91XXXXXXXXXX)",
                max_length=20,
                null=True,
            ),
        ),
    ]
