# Generated by Django 4.2.7 on 2025-11-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_add_mobile_number_to_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="security_answer",
            field=models.CharField(
                default="admin123",
                help_text="Answer to security question (case-insensitive)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="admin",
            name="security_question",
            field=models.CharField(
                default="What is the name of your first pet?",
                help_text="Security question for password recovery",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="registereddonor",
            name="security_answer",
            field=models.CharField(
                blank=True,
                help_text="Answer to security question (case-insensitive)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="registereddonor",
            name="security_question",
            field=models.CharField(
                blank=True,
                help_text="Security question for password recovery",
                max_length=200,
                null=True,
            ),
        ),
    ]
